version: '3'

services:
  helloworld:
    image: nginx:alpine
    hostname: nginx
    container_name: 'nginx'
    labels:
      - traefik.port=80
      - traefik.frontend.rule=Host:127.0.0.1; Path:/ ,PathPrefix:/
      - traefik.frontend.priority = 1

  reverse-proxy:
    image: traefik
    container_name: 'traefik'
    labels:
      - traefik.enable=false
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./logs:/logs
