version: '3'

services:
  whoami:
    image: emilevauge/whoami #A container that exposes an API to show it's IP address
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
  reverse-proxy:
    image: traefik
    command: --api --docker #Enables the web UI and tells Træfik to listen to docker
    ports:
      - "8090:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
